services:

  mysql:
    image: mysql:8
    container_name: user18-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: despacho_db
    ports:
      - "3318:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  ventas:
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
    container_name: user18-ventas-service
    depends_on:
      - mysql
    environment:
      DB_ENDPOINT: mysql
      DB_PORT: 3306
      DB_NAME: despacho_db
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - "8086:8080"

  despachos:
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    container_name: user18-despacho-service
    depends_on:
      - mysql
    environment:
      DB_ENDPOINT: mysql
      DB_PORT: 3306
      DB_NAME: despacho_db
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - "8087:8081"

  frontend:
    build:
      context: ./front_despacho
    container_name: user18-front-despacho
    depends_on:
      - ventas
      - despachos
    ports:
      - "3018:80"

volumes:
  mysql_data:
